In [2]:
print("Hello World")

Hello World

In [3]:
print("time for machine learning")

time for machine learning

In [4]:
import numpy as np
import pandas as pd

In [5]:
df= pd.read_csv("bike_prices_dataset.csv")
df.head()

,S.no,Bike_company,Bike_model,Manufactured_year,Engine_warranty,Engine_type,Fuel_type,CC(Cubic capacity),Fuel_Capacity,Price
0,1,Bajaj,Avenger 220,2020,5.0,Single,Petrol,220CC,10 Litres,113000
1,2,TVS,Apache RTR,2020,5.0,V-twin,Petrol,120CC,11 Litres,70000
2,3,Hero,Passion,2020,5.0,Boxer,Petrol,140CC,12 Litres,85000
3,4,Honda,Activa 3G,2020,5.0,Single,Petrol,150CC,13 Litres,90000
4,5,Suzuki,Access,2020,5.0,V-twin,Petrol,350CC,14 Litres,65000

In [6]:
df.tail()

,S.no,Bike_company,Bike_model,Manufactured_year,Engine_warranty,Engine_type,Fuel_type,CC(Cubic capacity),Fuel_Capacity,Price
303,304,Bgauss,Bgauss B8,2017,3.0,Boxer,Petrol,185CC,19 Litres,81916
304,305,Bgauss,Bgauss Radiator,2017,3.0,Boxer,Petrol,205CC,20 Litres,82666
305,306,Bgauss,Bgauss Razor,2017,3.0,Boxer,Petrol,185CC,21 Litres,83416
306,307,Bgauss,Bgauss Flash,2017,3.0,Boxer,Petrol,205CC,22 Litres,84166
307,308,Bgauss,Bgauss Hash,2017,3.0,Boxer,Petrol,220CC,23 Litres,84916

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308 entries, 0 to 307
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   S.no                308 non-null    int64
 1   Bike_company        308 non-null    object
 2   Bike_model          308 non-null    object
 3   Manufactured_year   308 non-null    int64
 4   Engine_warranty     306 non-null    float64
 5   Engine_type         308 non-null    object
 6   Fuel_type           308 non-null    object
 7   CC(Cubic capacity)  308 non-null    object
 8   Fuel_Capacity       307 non-null    object
 9   Price               308 non-null    int64
dtypes: float64(1), int64(3), object(6)
memory usage: 24.2+ KB

In [8]:
df.isna()

,S.no,Bike_company,Bike_model,Manufactured_year,Engine_warranty,Engine_type,Fuel_type,CC(Cubic capacity),Fuel_Capacity,Price
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
303,False,False,False,False,False,False,False,False,False,False
304,False,False,False,False,False,False,False,False,False,False
305,False,False,False,False,False,False,False,False,False,False
306,False,False,False,False,False,False,False,False,False,False
307,False,False,False,False,False,False,False,False,False,False

In [10]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
303    False
304    False
305    False
306    False
307    False
Length: 308, dtype: bool